
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry-manjuojal-dev.apps.sandbox.x8i5.p1.openshiftapps.com/eureka/
  instance:
    hostname: http://service-registry-manjuojal-dev.apps.sandbox.x8i5.p1.openshiftapps.com
